pipeline {
    agent any
    stages {
        stage('Submit Stack') {
            steps {
            sh "aws cloudformation create-stack --stack-name cluster1 --template-body file://simplests3cft.json --region 'us-south-1'"
              }
             }
            }
            }
